### ISSUE TITLE
Unhandled exception. System.Exception: Time has expired

### ISSUE THREAD

**Issue by enda2020** [hsakoh/broute-mqtt#1]
まず、このアドオンを作成していただきありがとうございます。非常に使いやすく便利です。 Google翻訳を使用して申し訳ありません。

数日間使用していますが、1日に10〜20回クラッシュします。以下のエラーによると、タイムアウトのようですが、理由はわかりません。無線接続が不良である可能性があります。

「Tessera Technology RL7023 Stick-D / DSS」を使用してHomeAssistantOSでアドオンを実行しています。

これまでにこのような問題を見たことがありますか?タイムアウト期間を設定可能にすることは可能でしょうか。
```

02:51:30 info: EchoDotNetLite.EchoClient[0] 0x0Eプロファイル 0xF0ノードプロファイル 01 プロパティマップの読み取りが成功しました
02:51:30 dbug: BRouteController.BRouteControllerService[0] 低圧スマート電力量メータ デバイスのGET対応プロパティの値をすべて取得
02:51:30 info: EchoDotNetLite.EchoClient[0] 0x0Eプロファイル 0xF0ノードプロファイル 01のプロパティ値を読み出します(0x80動作状態 Get(Req)  Anno)
02:51:31 info: BRouteController.BRouteControllerService[0] EchoProperty Change 0x80動作状態 Get(Req)  Anno 30
02:51:31 info: EchoDotNetLite.EchoClient[0] 0x0Eプロファイル 0xF0ノードプロファイル 01のプロパティ値を読み出します(0x81設置場所 Get(Req) Set(Req) Anno)
02:51:31 info: BRouteController.BRouteControllerService[0] EchoProperty Change 0x81設置場所 Get(Req) Set(Req) Anno 61
02:51:31 info: EchoDotNetLite.EchoClient[0] 0x0Eプロファイル 0xF0ノードプロファイル 01のプロパティ値を読み出します(0x88異常発生状態 Get(Req)  Anno)
02:51:32 info: BRouteController.BRouteControllerService[0] EchoProperty Change 0x88異常発生状態 Get(Req)  Anno 42
02:51:32 info: EchoDotNetLite.EchoClient[0] 0x0Eプロファイル 0xF0ノードプロファイル 01のプロパティ値を読み出します(0xE5積算履歴収集日１ Get(Req) Set(Req) )
02:51:32 info: BRouteController.BRouteControllerService[0] EchoProperty Change 0xE5積算履歴収集日１ Get(Req) Set(Req)  FF
02:51:32 info: EchoDotNetLite.EchoClient[0] 0x0Eプロファイル 0xF0ノードプロファイル 01のプロパティ値を読み出します(0xED積算履歴収集日２ Get Set )
02:51:32 info: BRouteController.BRouteControllerService[0] EchoProperty Change 0xED積算履歴収集日２ Get Set  FFFFFFFFFFFF01
02:51:32 info: EchoDotNetLite.EchoClient[0] 0x0Eプロファイル 0xF0ノードプロファイル 01のプロパティ値を読み出します(0xE0積算電力量計測値 (正方向計測値) Get(Req)  )
02:51:53 info: EchoDotNetLiteSkstackIpBridge.SkstackIpPANAClient[0] Close
02:51:53 info: SkstackIpDotNet.SKDevice[0] Close
Unhandled exception. System.Exception: Time has expired
   at EchoDotNetLite.EchoClient.プロパティ値読み出し(EchoObjectInstance sourceObject, EchoNode destinationNode, EchoObjectInstance destinationObject, IEnumerable`1 properties, Int32 timeoutMilliseconds) in C:\github\hsakoh\broute-mqtt\src\EchonetLite\EchoDotNetLite\Client.cs:line 328
   at BRouteController.BRouteControllerService.ReadAllPropertiesAsync(CancellationToken cs) in C:\github\hsakoh\broute-mqtt\src\BRouteController\BRouteControllerService.cs:line 252
   at BRouteController.BRouteControllerService.InitalizeAsync(CancellationToken ct) in C:\github\hsakoh\broute-mqtt\src\BRouteController\BRouteControllerService.cs:line 64
   at BRouteMqttApp.Worker.StartAsync(CancellationToken cancellationToken) in C:\github\hsakoh\broute-mqtt\src\BRouteMqttApp\Worker.cs:line 26
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at BRouteMqttApp.Program.Main(String[] args) in C:\github\hsakoh\broute-mqtt\src\BRouteMqttApp\Program.cs:line 35
```

**Comment by hsakoh** [comment]
フィードバックありがとうございます！
（このアドオンを使ってみようとする人がいたことに驚いています。
（そして、RL7023 Stick-D/IPSではなく、RL7023 Stick-D/DSSで動いている事にも驚きです。

>これまでにこのような問題を見たことがありますか?

はい。
提示いただいたログと同様に、プロパティ値読み出しで、タイムアウトになることは偶にありました。
電波環境が悪いか、スマートメーターの機種の違いによる性能差なのかもしれません。
私の環境では、タイムアウトが頻発した後、30分程度経つと改善されることが多く、特に問題視していませんでした。
（Wi-SUN USBスティックを指したデバイスを、スマートメーターの近くへ移動させると改善されたりするでしょうか？

>数日間使用していますが、1日に10〜20回クラッシュします。

上記記述から、ある程度は正常に使用できる時もあると理解しましたが、この理解は合っていますか？

>タイムアウト期間を設定可能にすることは可能でしょうか。

はい。
以下の変更を加えた、v1.0.3をリリースしました。

* PANスキャン/PANAコネクションのタイムアウトとリトライ回数を構成可能にしました。
   * v1.02まではv.1.0.3の既定値と同じ
* プロパティ値読み出し時のタイムアウト(既定値5秒)とリトライ回数(既定値3回)を構成可能にしました。
   * v1.02まではタイムアウトが20秒、リトライなし
・アドオン起動時の連続プロパティ値読み出しで、コマンド間に2秒のディレイを追加しました。
   * v1.02までは0秒
・ポーリング時にエラーが発生した場合、処理を継続するオプションを追加しました。
   * v1.02まではアドオンアプリが異常終了

---
今回、タイムアウトの時間を変更可能としましたが…
経験的には、2秒以内に応答がない場合、どれだけ待っても スマートメーターが応答を返してくれたことがないので、
v1.0.2でも既に20秒間の待機をしていたことから、タイムアウトを伸ばしても改善しない気がしています。

再現頻度が高くないため、タイムアウトが発生した場合に、
「読み出しコマンドの再送信で改善」するのか、「再接続が必要」なのか が分かっていません…。

v1.0.2までは、タイムアウトが発生した場合、アドオンを（意図的に）未処理の例外で終了させ、HA-OS側でウォッチドッグを有効にしておき、アドオンを自動的に再起動させることで、スマートメーターへ再接続するという流れを想定したつくりでした。

今回、リトライを実装したため、「読み出しコマンドの再送信で改善」するのであれば、これで改善されると思います。

もし、「再接続が必要」な場合は、また違う修正が必要です。修正量が多くなるため、一旦見送りました。
---

まずは一度 v1.0.3にアップデートして、改善されるか確認いただけますか。

追加になった構成値は、タイムアウトよりリトライの方が効果があると思うので、まずは既定値で試して頂ければと思います。
私の環境だとなかなか再現や改善が確認できないので、ぜひ再びフィードバックをいただきたいです。

それで改善しなければ、タイムアウトを延ばし、ContinuePollingOnErrorを`false`にして、まずはご使用ください。
「再接続が必要」であると思われるので、再接続処理を実装した改善版をリリースするまでは、アドオンの再起動で再接続させる事を意図しています。

ウォッチドッグは引き続き有効に設定してください。

**Comment by enda2020** [comment]
迅速な対応をありがとうございました。大変ありがたく思っています。

アドオンを更新し、すべてをデフォルトのままにしました (構成を更新していません)。一晩中完璧に動作し、クラッシュや例外は 1 つも発生していません。

以前はウォッチドッグを有効にしていましたが、30 分以内に 10 回以上クラッシュし、スーパーバイザーが再起動を拒否することがありました。修正するためにいくつかの自動化を試しましたが、信頼性がありませんでした。

申し訳ありませんが、以前は間違っていました。RL7023 Stick-D/IPS を使用しています。

https://www.chip1stop.com/JPN/en/view/dispDetail/DispDetail?partId=TSRA-0000042&keyword=C1S755400000427

![image](https://github.com/hsakoh/broute-mqtt/assets/61083333/70f41990-426e-4c0a-9eda-f334b28dd1f6)

Broute Configuration

Id: XXXXXXXXXXXXXX
Pw: XXXXXXXXXXXXXXXX
SerialPort: /dev/ttyUSB0
ForcePANScan: false
PanDescSavePath: /data/EPANDESC.json
InstantaneousValueInterval: "00:01:10"
PanScanMaxRetryAttempts: 3
PanScanRetryDelay: "00:01:00"
PanaConnectTimeout: "00:00:30"
PanaConnectMaxRetryAttempts: 3
PanaConnectRetryDelay: "00:01:00"
PropertyReadTimeout: "00:00:05"
PropertyReadMaxRetryAttempts: 3
PropertyReadRetryDelay: "00:00:05"
ContinuePollingOnError: true

**Comment by hsakoh** [comment]
なるほど、クラッシュ回数が多いとスーパーバイザーがそういう挙動をするんですね 知りませんでした。勉強になりました。

とりあえず一晩無事に動いたとの事、よかったです。

タイムアウト・リトライが発生した場合、WarningやErrorレベルでログを出しています。
Infoレベルのログによって、WarningやErrorレベルのログが流れているかもしれないので、
ログレベルをWarningに設定すると、「リトライの追加」と「コマンド間隔の追加」どちらが改善に効果があったか観察できるかなと思いました。
（リトライが発生していればリトライの追加に効果があった、リトライが無ければコマンド間隔の追加に効果があった か、電波状況等で元の問題が発生していない…等
